/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedOrgSlugLayoutRouteRouteImport } from './routes/_authenticated/org.$slug/_layout/route'
import { Route as AuthenticatedOrgSlugLayoutIndexRouteImport } from './routes/_authenticated/org.$slug/_layout/index'
import { Route as AuthenticatedOrgSlugLayoutSettingsRouteImport } from './routes/_authenticated/org.$slug/_layout/settings'
import { Route as AuthenticatedOrgSlugLayoutMeRouteImport } from './routes/_authenticated/org.$slug/_layout/me'
import { Route as AuthenticatedOrgSlugLayoutDangerRouteImport } from './routes/_authenticated/org.$slug/_layout/danger'
import { Route as AuthenticatedOrgSlugLayoutArchiveRouteImport } from './routes/_authenticated/org.$slug/_layout/archive'
import { Route as AuthenticatedOrgSlugLayoutAuditRouteRouteImport } from './routes/_authenticated/org.$slug/_layout/audit/route'
import { Route as AuthenticatedOrgSlugLayoutProjectsIndexRouteImport } from './routes/_authenticated/org.$slug/_layout/projects/index'
import { Route as AuthenticatedOrgSlugLayoutMembersIndexRouteImport } from './routes/_authenticated/org.$slug/_layout/members.index'
import { Route as AuthenticatedOrgSlugLayoutAuditIndexRouteImport } from './routes/_authenticated/org.$slug/_layout/audit/index'
import { Route as AuthenticatedOrgSlugLayoutMembersIdRouteImport } from './routes/_authenticated/org.$slug/_layout/members.$id'
import { Route as AuthenticatedOrgSlugLayoutAuditSecurityRouteImport } from './routes/_authenticated/org.$slug/_layout/audit/security'
import { Route as AuthenticatedOrgSlugLayoutAuditInvitationsRouteImport } from './routes/_authenticated/org.$slug/_layout/audit/invitations'
import { Route as AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRouteImport } from './routes/_authenticated/org.$slug/_layout/projects/$projectId/_layout'
import { Route as AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutIndexRouteImport } from './routes/_authenticated/org.$slug/_layout/projects/$projectId/_layout/index'
import { Route as AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutSettingsRouteImport } from './routes/_authenticated/org.$slug/_layout/projects/$projectId/_layout/settings'
import { Route as AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutMembersRouteImport } from './routes/_authenticated/org.$slug/_layout/projects/$projectId/_layout/members'
import { Route as AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutApiKeysRouteImport } from './routes/_authenticated/org.$slug/_layout/projects/$projectId/_layout/api-keys'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgSlugLayoutRouteRoute =
  AuthenticatedOrgSlugLayoutRouteRouteImport.update({
    id: '/org/$slug/_layout',
    path: '/org/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutIndexRoute =
  AuthenticatedOrgSlugLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgSlugLayoutRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutSettingsRoute =
  AuthenticatedOrgSlugLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrgSlugLayoutRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutMeRoute =
  AuthenticatedOrgSlugLayoutMeRouteImport.update({
    id: '/me',
    path: '/me',
    getParentRoute: () => AuthenticatedOrgSlugLayoutRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutDangerRoute =
  AuthenticatedOrgSlugLayoutDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => AuthenticatedOrgSlugLayoutRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutArchiveRoute =
  AuthenticatedOrgSlugLayoutArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => AuthenticatedOrgSlugLayoutRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutAuditRouteRoute =
  AuthenticatedOrgSlugLayoutAuditRouteRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedOrgSlugLayoutRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutProjectsIndexRoute =
  AuthenticatedOrgSlugLayoutProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedOrgSlugLayoutRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutMembersIndexRoute =
  AuthenticatedOrgSlugLayoutMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedOrgSlugLayoutRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutAuditIndexRoute =
  AuthenticatedOrgSlugLayoutAuditIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgSlugLayoutAuditRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutMembersIdRoute =
  AuthenticatedOrgSlugLayoutMembersIdRouteImport.update({
    id: '/members/$id',
    path: '/members/$id',
    getParentRoute: () => AuthenticatedOrgSlugLayoutRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutAuditSecurityRoute =
  AuthenticatedOrgSlugLayoutAuditSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedOrgSlugLayoutAuditRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutAuditInvitationsRoute =
  AuthenticatedOrgSlugLayoutAuditInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedOrgSlugLayoutAuditRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRoute =
  AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRouteImport.update({
    id: '/projects/$projectId/_layout',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedOrgSlugLayoutRouteRoute,
  } as any)
const AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutIndexRoute =
  AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRoute,
  } as any)
const AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutSettingsRoute =
  AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () =>
      AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRoute,
  } as any)
const AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutMembersRoute =
  AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () =>
      AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRoute,
  } as any)
const AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutApiKeysRoute =
  AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () =>
      AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/org/$slug': typeof AuthenticatedOrgSlugLayoutRouteRouteWithChildren
  '/org/$slug/audit': typeof AuthenticatedOrgSlugLayoutAuditRouteRouteWithChildren
  '/org/$slug/archive': typeof AuthenticatedOrgSlugLayoutArchiveRoute
  '/org/$slug/danger': typeof AuthenticatedOrgSlugLayoutDangerRoute
  '/org/$slug/me': typeof AuthenticatedOrgSlugLayoutMeRoute
  '/org/$slug/settings': typeof AuthenticatedOrgSlugLayoutSettingsRoute
  '/org/$slug/': typeof AuthenticatedOrgSlugLayoutIndexRoute
  '/org/$slug/audit/invitations': typeof AuthenticatedOrgSlugLayoutAuditInvitationsRoute
  '/org/$slug/audit/security': typeof AuthenticatedOrgSlugLayoutAuditSecurityRoute
  '/org/$slug/members/$id': typeof AuthenticatedOrgSlugLayoutMembersIdRoute
  '/org/$slug/audit/': typeof AuthenticatedOrgSlugLayoutAuditIndexRoute
  '/org/$slug/members/': typeof AuthenticatedOrgSlugLayoutMembersIndexRoute
  '/org/$slug/projects/': typeof AuthenticatedOrgSlugLayoutProjectsIndexRoute
  '/org/$slug/projects/$projectId': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRouteWithChildren
  '/org/$slug/projects/$projectId/api-keys': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutApiKeysRoute
  '/org/$slug/projects/$projectId/members': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutMembersRoute
  '/org/$slug/projects/$projectId/settings': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutSettingsRoute
  '/org/$slug/projects/$projectId/': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/org/$slug/archive': typeof AuthenticatedOrgSlugLayoutArchiveRoute
  '/org/$slug/danger': typeof AuthenticatedOrgSlugLayoutDangerRoute
  '/org/$slug/me': typeof AuthenticatedOrgSlugLayoutMeRoute
  '/org/$slug/settings': typeof AuthenticatedOrgSlugLayoutSettingsRoute
  '/org/$slug': typeof AuthenticatedOrgSlugLayoutIndexRoute
  '/org/$slug/audit/invitations': typeof AuthenticatedOrgSlugLayoutAuditInvitationsRoute
  '/org/$slug/audit/security': typeof AuthenticatedOrgSlugLayoutAuditSecurityRoute
  '/org/$slug/members/$id': typeof AuthenticatedOrgSlugLayoutMembersIdRoute
  '/org/$slug/audit': typeof AuthenticatedOrgSlugLayoutAuditIndexRoute
  '/org/$slug/members': typeof AuthenticatedOrgSlugLayoutMembersIndexRoute
  '/org/$slug/projects': typeof AuthenticatedOrgSlugLayoutProjectsIndexRoute
  '/org/$slug/projects/$projectId/api-keys': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutApiKeysRoute
  '/org/$slug/projects/$projectId/members': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutMembersRoute
  '/org/$slug/projects/$projectId/settings': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutSettingsRoute
  '/org/$slug/projects/$projectId': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_landing': typeof LandingRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_landing/': typeof LandingIndexRoute
  '/_authenticated/org/$slug/_layout': typeof AuthenticatedOrgSlugLayoutRouteRouteWithChildren
  '/_authenticated/org/$slug/_layout/audit': typeof AuthenticatedOrgSlugLayoutAuditRouteRouteWithChildren
  '/_authenticated/org/$slug/_layout/archive': typeof AuthenticatedOrgSlugLayoutArchiveRoute
  '/_authenticated/org/$slug/_layout/danger': typeof AuthenticatedOrgSlugLayoutDangerRoute
  '/_authenticated/org/$slug/_layout/me': typeof AuthenticatedOrgSlugLayoutMeRoute
  '/_authenticated/org/$slug/_layout/settings': typeof AuthenticatedOrgSlugLayoutSettingsRoute
  '/_authenticated/org/$slug/_layout/': typeof AuthenticatedOrgSlugLayoutIndexRoute
  '/_authenticated/org/$slug/_layout/audit/invitations': typeof AuthenticatedOrgSlugLayoutAuditInvitationsRoute
  '/_authenticated/org/$slug/_layout/audit/security': typeof AuthenticatedOrgSlugLayoutAuditSecurityRoute
  '/_authenticated/org/$slug/_layout/members/$id': typeof AuthenticatedOrgSlugLayoutMembersIdRoute
  '/_authenticated/org/$slug/_layout/audit/': typeof AuthenticatedOrgSlugLayoutAuditIndexRoute
  '/_authenticated/org/$slug/_layout/members/': typeof AuthenticatedOrgSlugLayoutMembersIndexRoute
  '/_authenticated/org/$slug/_layout/projects/': typeof AuthenticatedOrgSlugLayoutProjectsIndexRoute
  '/_authenticated/org/$slug/_layout/projects/$projectId/_layout': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRouteWithChildren
  '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/api-keys': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutApiKeysRoute
  '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/members': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutMembersRoute
  '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/settings': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutSettingsRoute
  '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/': typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/invite/$token'
    | '/org/$slug'
    | '/org/$slug/audit'
    | '/org/$slug/archive'
    | '/org/$slug/danger'
    | '/org/$slug/me'
    | '/org/$slug/settings'
    | '/org/$slug/'
    | '/org/$slug/audit/invitations'
    | '/org/$slug/audit/security'
    | '/org/$slug/members/$id'
    | '/org/$slug/audit/'
    | '/org/$slug/members/'
    | '/org/$slug/projects/'
    | '/org/$slug/projects/$projectId'
    | '/org/$slug/projects/$projectId/api-keys'
    | '/org/$slug/projects/$projectId/members'
    | '/org/$slug/projects/$projectId/settings'
    | '/org/$slug/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/invite/$token'
    | '/org/$slug/archive'
    | '/org/$slug/danger'
    | '/org/$slug/me'
    | '/org/$slug/settings'
    | '/org/$slug'
    | '/org/$slug/audit/invitations'
    | '/org/$slug/audit/security'
    | '/org/$slug/members/$id'
    | '/org/$slug/audit'
    | '/org/$slug/members'
    | '/org/$slug/projects'
    | '/org/$slug/projects/$projectId/api-keys'
    | '/org/$slug/projects/$projectId/members'
    | '/org/$slug/projects/$projectId/settings'
    | '/org/$slug/projects/$projectId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_landing'
    | '/auth'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/auth/login'
    | '/auth/register'
    | '/invite/$token'
    | '/_landing/'
    | '/_authenticated/org/$slug/_layout'
    | '/_authenticated/org/$slug/_layout/audit'
    | '/_authenticated/org/$slug/_layout/archive'
    | '/_authenticated/org/$slug/_layout/danger'
    | '/_authenticated/org/$slug/_layout/me'
    | '/_authenticated/org/$slug/_layout/settings'
    | '/_authenticated/org/$slug/_layout/'
    | '/_authenticated/org/$slug/_layout/audit/invitations'
    | '/_authenticated/org/$slug/_layout/audit/security'
    | '/_authenticated/org/$slug/_layout/members/$id'
    | '/_authenticated/org/$slug/_layout/audit/'
    | '/_authenticated/org/$slug/_layout/members/'
    | '/_authenticated/org/$slug/_layout/projects/'
    | '/_authenticated/org/$slug/_layout/projects/$projectId/_layout'
    | '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/api-keys'
    | '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/members'
    | '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/settings'
    | '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/$slug/_layout': {
      id: '/_authenticated/org/$slug/_layout'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/$slug/_layout/': {
      id: '/_authenticated/org/$slug/_layout/'
      path: '/'
      fullPath: '/org/$slug/'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutRouteRoute
    }
    '/_authenticated/org/$slug/_layout/settings': {
      id: '/_authenticated/org/$slug/_layout/settings'
      path: '/settings'
      fullPath: '/org/$slug/settings'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutSettingsRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutRouteRoute
    }
    '/_authenticated/org/$slug/_layout/me': {
      id: '/_authenticated/org/$slug/_layout/me'
      path: '/me'
      fullPath: '/org/$slug/me'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutMeRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutRouteRoute
    }
    '/_authenticated/org/$slug/_layout/danger': {
      id: '/_authenticated/org/$slug/_layout/danger'
      path: '/danger'
      fullPath: '/org/$slug/danger'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutDangerRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutRouteRoute
    }
    '/_authenticated/org/$slug/_layout/archive': {
      id: '/_authenticated/org/$slug/_layout/archive'
      path: '/archive'
      fullPath: '/org/$slug/archive'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutArchiveRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutRouteRoute
    }
    '/_authenticated/org/$slug/_layout/audit': {
      id: '/_authenticated/org/$slug/_layout/audit'
      path: '/audit'
      fullPath: '/org/$slug/audit'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutAuditRouteRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutRouteRoute
    }
    '/_authenticated/org/$slug/_layout/projects/': {
      id: '/_authenticated/org/$slug/_layout/projects/'
      path: '/projects'
      fullPath: '/org/$slug/projects/'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutRouteRoute
    }
    '/_authenticated/org/$slug/_layout/members/': {
      id: '/_authenticated/org/$slug/_layout/members/'
      path: '/members'
      fullPath: '/org/$slug/members/'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutMembersIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutRouteRoute
    }
    '/_authenticated/org/$slug/_layout/audit/': {
      id: '/_authenticated/org/$slug/_layout/audit/'
      path: '/'
      fullPath: '/org/$slug/audit/'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutAuditIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutAuditRouteRoute
    }
    '/_authenticated/org/$slug/_layout/members/$id': {
      id: '/_authenticated/org/$slug/_layout/members/$id'
      path: '/members/$id'
      fullPath: '/org/$slug/members/$id'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutMembersIdRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutRouteRoute
    }
    '/_authenticated/org/$slug/_layout/audit/security': {
      id: '/_authenticated/org/$slug/_layout/audit/security'
      path: '/security'
      fullPath: '/org/$slug/audit/security'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutAuditSecurityRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutAuditRouteRoute
    }
    '/_authenticated/org/$slug/_layout/audit/invitations': {
      id: '/_authenticated/org/$slug/_layout/audit/invitations'
      path: '/invitations'
      fullPath: '/org/$slug/audit/invitations'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutAuditInvitationsRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutAuditRouteRoute
    }
    '/_authenticated/org/$slug/_layout/projects/$projectId/_layout': {
      id: '/_authenticated/org/$slug/_layout/projects/$projectId/_layout'
      path: '/projects/$projectId'
      fullPath: '/org/$slug/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutRouteRoute
    }
    '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/': {
      id: '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/'
      path: '/'
      fullPath: '/org/$slug/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRoute
    }
    '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/settings': {
      id: '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/settings'
      path: '/settings'
      fullPath: '/org/$slug/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutSettingsRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRoute
    }
    '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/members': {
      id: '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/members'
      path: '/members'
      fullPath: '/org/$slug/projects/$projectId/members'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutMembersRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRoute
    }
    '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/api-keys': {
      id: '/_authenticated/org/$slug/_layout/projects/$projectId/_layout/api-keys'
      path: '/api-keys'
      fullPath: '/org/$slug/projects/$projectId/api-keys'
      preLoaderRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutApiKeysRouteImport
      parentRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRoute
    }
  }
}

interface AuthenticatedOrgSlugLayoutAuditRouteRouteChildren {
  AuthenticatedOrgSlugLayoutAuditInvitationsRoute: typeof AuthenticatedOrgSlugLayoutAuditInvitationsRoute
  AuthenticatedOrgSlugLayoutAuditSecurityRoute: typeof AuthenticatedOrgSlugLayoutAuditSecurityRoute
  AuthenticatedOrgSlugLayoutAuditIndexRoute: typeof AuthenticatedOrgSlugLayoutAuditIndexRoute
}

const AuthenticatedOrgSlugLayoutAuditRouteRouteChildren: AuthenticatedOrgSlugLayoutAuditRouteRouteChildren =
  {
    AuthenticatedOrgSlugLayoutAuditInvitationsRoute:
      AuthenticatedOrgSlugLayoutAuditInvitationsRoute,
    AuthenticatedOrgSlugLayoutAuditSecurityRoute:
      AuthenticatedOrgSlugLayoutAuditSecurityRoute,
    AuthenticatedOrgSlugLayoutAuditIndexRoute:
      AuthenticatedOrgSlugLayoutAuditIndexRoute,
  }

const AuthenticatedOrgSlugLayoutAuditRouteRouteWithChildren =
  AuthenticatedOrgSlugLayoutAuditRouteRoute._addFileChildren(
    AuthenticatedOrgSlugLayoutAuditRouteRouteChildren,
  )

interface AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRouteChildren {
  AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutApiKeysRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutApiKeysRoute
  AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutMembersRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutMembersRoute
  AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutSettingsRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutSettingsRoute
  AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutIndexRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutIndexRoute
}

const AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRouteChildren: AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRouteChildren =
  {
    AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutApiKeysRoute:
      AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutApiKeysRoute,
    AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutMembersRoute:
      AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutMembersRoute,
    AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutSettingsRoute:
      AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutSettingsRoute,
    AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutIndexRoute:
      AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutIndexRoute,
  }

const AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRouteWithChildren =
  AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRoute._addFileChildren(
    AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRouteChildren,
  )

interface AuthenticatedOrgSlugLayoutRouteRouteChildren {
  AuthenticatedOrgSlugLayoutAuditRouteRoute: typeof AuthenticatedOrgSlugLayoutAuditRouteRouteWithChildren
  AuthenticatedOrgSlugLayoutArchiveRoute: typeof AuthenticatedOrgSlugLayoutArchiveRoute
  AuthenticatedOrgSlugLayoutDangerRoute: typeof AuthenticatedOrgSlugLayoutDangerRoute
  AuthenticatedOrgSlugLayoutMeRoute: typeof AuthenticatedOrgSlugLayoutMeRoute
  AuthenticatedOrgSlugLayoutSettingsRoute: typeof AuthenticatedOrgSlugLayoutSettingsRoute
  AuthenticatedOrgSlugLayoutIndexRoute: typeof AuthenticatedOrgSlugLayoutIndexRoute
  AuthenticatedOrgSlugLayoutMembersIdRoute: typeof AuthenticatedOrgSlugLayoutMembersIdRoute
  AuthenticatedOrgSlugLayoutMembersIndexRoute: typeof AuthenticatedOrgSlugLayoutMembersIndexRoute
  AuthenticatedOrgSlugLayoutProjectsIndexRoute: typeof AuthenticatedOrgSlugLayoutProjectsIndexRoute
  AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRoute: typeof AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRouteWithChildren
}

const AuthenticatedOrgSlugLayoutRouteRouteChildren: AuthenticatedOrgSlugLayoutRouteRouteChildren =
  {
    AuthenticatedOrgSlugLayoutAuditRouteRoute:
      AuthenticatedOrgSlugLayoutAuditRouteRouteWithChildren,
    AuthenticatedOrgSlugLayoutArchiveRoute:
      AuthenticatedOrgSlugLayoutArchiveRoute,
    AuthenticatedOrgSlugLayoutDangerRoute:
      AuthenticatedOrgSlugLayoutDangerRoute,
    AuthenticatedOrgSlugLayoutMeRoute: AuthenticatedOrgSlugLayoutMeRoute,
    AuthenticatedOrgSlugLayoutSettingsRoute:
      AuthenticatedOrgSlugLayoutSettingsRoute,
    AuthenticatedOrgSlugLayoutIndexRoute: AuthenticatedOrgSlugLayoutIndexRoute,
    AuthenticatedOrgSlugLayoutMembersIdRoute:
      AuthenticatedOrgSlugLayoutMembersIdRoute,
    AuthenticatedOrgSlugLayoutMembersIndexRoute:
      AuthenticatedOrgSlugLayoutMembersIndexRoute,
    AuthenticatedOrgSlugLayoutProjectsIndexRoute:
      AuthenticatedOrgSlugLayoutProjectsIndexRoute,
    AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRoute:
      AuthenticatedOrgSlugLayoutProjectsProjectIdLayoutRouteWithChildren,
  }

const AuthenticatedOrgSlugLayoutRouteRouteWithChildren =
  AuthenticatedOrgSlugLayoutRouteRoute._addFileChildren(
    AuthenticatedOrgSlugLayoutRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedOrgSlugLayoutRouteRoute: typeof AuthenticatedOrgSlugLayoutRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedOrgSlugLayoutRouteRoute:
    AuthenticatedOrgSlugLayoutRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LandingRouteRouteChildren {
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
